### ISSUE TITLE
Container Healthcheck states that the gateway is running when it is still starting

### ISSUE THREAD

**Issue by kgamble96** [thirdgen88/ignition-docker#24]
The 8.0.12 containers always show running from the moment that a localhost:<port>/StatusPing is able to be recieved, so I am not positive if its checking for the Running tag

I think that it is because the healthcheck is listed as 
`HEALTHCHECK --interval=10s --start-period=60s --timeout=3s \
    CMD curl -f http://localhost:8088/StatusPing 2>&1 | grep RUNNING`

and not 

`HEALTHCHECK --interval=10s --start-period=60s --timeout=3s \
    CMD curl -f http://localhost:8088/StatusPing 2>&1 | grep RUNNING > /dev/null`

**Comment by thirdgen88** [comment]
I've taken a look at this, and the behavior seems to be correct from what I can observe.  Take a look at the run example below where I've got the `docker run` at the top, a running `docker ps` in the middle, and an example of the `curl` output in the bottom pane:

![healthcheck3](https://user-images.githubusercontent.com/7111175/84456284-35869000-ac25-11ea-895b-ed709803b31f.gif)

As you can see there, the health status from `docker ps` stays in `health: starting` status until we finally reach `"state": "RUNNING"` from the `curl` request (there is a slight delay since the health check is configured to run only every 10s).  Can you provide more details on your run context?  (OS, where/how you're launching the container, etc)

**Comment by kgamble96** [comment]
Actually it looks like this is a bug with Docker Desktop for windows! When I take a look at the container status with `docker ps` then it correctly shows starting.
