### ISSUE TITLE
Maker activation support

### ISSUE THREAD

**Issue by frostydaze** [thirdgen88/ignition-docker#30]
During first run Maker edition is not being activated and always has 'Activate Ignition"

Have regen'd key and token and gone though docker-entrypoint.sh to force commissioning phase.

**Comment by thirdgen88** [comment]
@frostydaze can you add your `docker run` or equivalent so I can try to see about reproducing?  Any logs (including the provisioning.log) would be helpful too.

**Comment by frostydaze** [comment]
Sorry I didn't include more detail initially, far too late at night.

I am running under a Ubuntu 20.02LTS VirtualBox with Win 10 Host (so don't think I can send provision.log), 

My docker run is as follows (omitted password, key and token details) 

docker run -p 8088:8088 --name my-ignition-maker \
     -v my-ignition-data:/var/lib/ignition/data \
    -e GATEWAY_ADMIN_PASSWORD=xxxx \
    -e IGNITION_EDITION=maker \
    -e IGNITION_LICENSE_KEY=xxxx-xxxx \
    -e IGNITION_ACTIVATION_TOKEN=xxxxxx \
    -d kcollins/ignition:8.0.14

Container starts without error and can docker build without error

Manually entered the activation and under licence in gateway and have an error message to show that it is the standard version (attached)

![MakerAct_20200715](https://user-images.githubusercontent.com/32808976/87442980-423d4000-c638-11ea-9815-f49eb49f564b.png)

**Comment by thirdgen88** [comment]
@frostydaze, your Docker _run_ command looks just fine, I just spooled up another one using the same command line syntax and everything came up just fine.  One thing that I hesitate to ask is whether you're sure that you're opening up the container instance within your VM?  Is it Ubuntu Desktop?  I ask only because I've seen some confusion in the past where if you are running in a dedicated VM (without Docker integrations between guest/host that come with something like Docker Desktop), it is easy to _think_ you're hitting your container when you're actually inadvertently hitting a gateway you had installed on your host system.  

The _kcollins/ignition_ image automates the commissioning process, so you shouldn't have to select the edition or enter any of the license/activation information (for Maker).  If you're good so far and nothing I've mentioned above rings any alarm bells, I suppose the next step would be for you to perhaps post the first few lines of the container logs:

```
docker logs --until 1m my-ignition-maker
```

Also, fwiw, it looks like the gateway you pictured above in your screenshot is in _Full_ edition, not Maker.  That is why it is not happy about the license that was applied.  The log retrieved via the command above should help, it _should_ look something like this when everything works as intended:

```
$ docker logs --until 1m my-ignition-maker
Provisioning will be logged here: /usr/local/share/ignition/logs/provisioning.log
Waiting for commissioning servlet to become active...
Performing commissioning actions...
  IGNITION_EDITION: maker
  EULA_STATUS: accepted
  IGNITION_LICENSE_KEY: xxxx-xxxx
  GATEWAY_ADMIN_USERNAME: admin
  GATEWAY_HTTP_PORT: 8088
  GATEWAY_HTTPS_PORT: 8043
  START GATEWAY: issued
Shutting down interim provisioning gateway...
Processing Module Enable/Disable...
Starting Ignition Gateway...
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Standard Edition 64-bit 3.5.35
wrapper  |   Copyright (C) 1999-2018 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |   Licensed to Inductive Automation for Inductive Automation
wrapper  |
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | 02:21:26,382 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
jvm 1    | 02:21:26,401 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SysoutAppender]
jvm 1    | 02:21:26,420 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
jvm 1    | 02:21:26,499 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.inductiveautomation.logging.SQLiteAppender]
jvm 1    | 02:21:26,529 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [DB]
...
```

**Comment by frostydaze** [comment]
Please question everything, must be missing something simple. I don't have any other instances of Ignition installed on either the host or VM (Ubuntu Desktop)

I have attached my log from startup and it always seems to miss the commissioning, hence haven't been able to find provisioning.log inside container.

I have attached the log from where I deleted all previous images/containers and ran the docker run as per previous message.

[igmakerlog_20200722.log](https://github.com/thirdgen88/ignition-docker/files/4954259/igmakerlog_20200722.log)

I have also just noticed that my log is disabling services where yours is not?

The only time I have had anything else other appear in the log about commissioning was where I had downloaded the 8.0.13 version and then upgraded with 8.0.14 and from memory it rejected my key as it was already activated (but that may of been because it was Full version)

**Comment by frostydaze** [comment]
Update - It is working now, the only problem is I don't know why. I re-deleted all of the images present and freshly ran the same docker run on the same VM with same config, worked as expected to create a Maker container?

In any case thank you for putting this together and supporting the usage of it for all.
